services:
  - type: web
    name: mmfood-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: WEBHOOK_SECRET
        generateValue: true
